name: Create package version

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      promote:
        description: "Promote package version to released"
        type: boolean
        default: false
        required: true

jobs:
  package:
    uses: wtaxco/wtax-github-actions-workflows/.github/workflows/create-sfdx-package.yml@main
    with:
      promote: ${{ inputs.promote != null && inputs.promote }}
      sonar-quality-gate: true
    secrets:
      ansible-vault-password: ${{ secrets.VAULT_PASSWORD }}